### ISSUE TITLE
Ansible Intro Galaxy start command discrepancy

### ISSUE THREAD

**Issue by stevekm** [martenson/dagobah-training#16]
In the Ansible intro here:

https://github.com/martenson/dagobah-training/blob/master/advanced/001-ansible/ex1-intro-ansible.md

Instructions say to start Galaxy like this:

> 
> Once, that is complete you can start your Galaxy server to test it.
> 
>     Start the server with `sh ./run.sh --pid-file=main.pid --log-file=main.log --daemon`
> 

But in the `roles/galaxy-tool-install/defaults/main.yml` file, the following are set

> ```
> #The Galaxy pid and log file names.
> galaxy_pid_file: paster.pid
> galaxy_log_file: paster.log
> 
> ```
> 

I think either the pid and log file names need to be changed here, or the command to start Galaxy should be:

`sh ./run.sh --pid-file=paster.pid --log-file=paster.log --daemon`

**Comment by blankenberg** [comment]
Great catch. Fixed in https://github.com/martenson/dagobah-training/pull/15. Thanks!
